SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet;


-- Tables

CREATE TABLE compte(
   idCompte INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
   nom VARCHAR(50) NOT NULL,
   prenom VARCHAR(50),
   adresseMail VARCHAR(50) NOT NULL,
   motDePasse VARCHAR(50) NOT NULL,
   solde NUMERIC(15,2),
   admin BOOLEAN NOT NULL,
   PRIMARY KEY(idCompte)
);

CREATE TABLE parcelle(
   idParcelle INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
   surface DOUBLE PRECISION NOT NULL,
   libre BOOLEAN NOT NULL,
   idCompte INTEGER,
   PRIMARY KEY(idParcelle),
   FOREIGN KEY(idCompte) REFERENCES compte(idCompte)
);

CREATE TABLE mouvement(
   idMouvement INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
   date_ DATE NOT NULL,
   libelle VARCHAR(50) NOT NULL,
   montant NUMERIC(15,2) NOT NULL,
   idCompte INTEGER NOT NULL,
   PRIMARY KEY(idMouvement),
   FOREIGN KEY(idCompte) REFERENCES compte(idCompte)
);

CREATE TABLE culture(
   idCulture INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
   nom VARCHAR(50) NOT NULL,
   PRIMARY KEY(idCulture)
);

CREATE TABLE entretien(
   idEntretien INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
   date_ DATE NOT NULL,
   titre VARCHAR(50) NOT NULL,
   PRIMARY KEY(idEntretien)
);

CREATE TABLE contenir(
   idParcelle INTEGER,
   idCulture INTEGER,
   part NUMERIC(5,2),
   PRIMARY KEY(idParcelle, idCulture),
   FOREIGN KEY(idParcelle) REFERENCES parcelle(idParcelle),
   FOREIGN KEY(idCulture) REFERENCES culture(idCulture)
);

CREATE TABLE concerner(
   idCulture INTEGER,
   idEntretien INTEGER,
   PRIMARY KEY(idCulture, idEntretien),
   FOREIGN KEY(idCulture) REFERENCES culture(idCulture),
   FOREIGN KEY(idEntretien) REFERENCES entretien(idEntretien)
);
